Update with all *real* models
jdiaz4302/lake_ice_prediction pull request #13
Opened 2022-10-14 16:59 UTC by jdiaz4302

Just prior to this PR I merged a dummy PR into main which duplicated the `02_train/src/A` notebook into an A, B, C, D, E, and F version. This PR is about adding the actual models into those dummy duplicates.

# Overview

`A`, `C`, and `E` are LSTM notebooks. Later letters correspond to larger model sizes: `A` = average, `C` = 3 million parameters, and `E` = 6 layers, 3 million parameters each, 18 million total. `B`, `D`, and `F` are transformer notebooks; their ordered letters follow the same size scheme.

* `A` and `B` were chosen to match the approximate normal size of an LSTM in hydrology/IIDD work.
* `F` is the original size of the full encoder (6 layers) in the original transformer paper. `E` is an LSTM with equivalent layers and total number of parameters.
  * There is no autoregression in this lake ice prediction (i.e., I'm not using past lake ice values to predict future lake ice), so an encoder-only approach seemed most applicable as a transformer model. This essentially replaces recurrence with self-attention on the exogenous variables. 
* `C` and `D` are 1-layer equivalents of `E` and `F`.

# Caveat

Not much actually changes between these notebooks. Realistically, these 6 notebooks could be 1 notebook, but it was easier during development to have 6 notebooks rather than 1 really flexible notebook. If any substantive changes need to made, I will likely consolidate them into 1 notebook, but I would rather make as little polishing/design changes as necessary at this point.

# Tips for reviewing

Much of what changes in each notebook is:

* Input values - batch size (to maximize GPU RAM), number of parameters/hidden layer size, number of layers, and file paths (e.g., `massive_lstm`)
* Model code - this is largely identical within model types. The "massive" notebooks are altered to allow a specification of number of layers
* Model definition (e.g., specifying number of layers)

# Requested review

Identification of bugs or erroneous implementation. Everything seems to be working as expected for many iterations at this point, but with transformers being new to us, it may be worth taking a closer look at their implementation and usage.

2022-10-14 17:02 UTC, jdiaz4302 commented on 02_train/src/B_FitBasicTransformer.ipynb
> +    "        return self.dropout(x)"
This is a standard sinusoidal positional encoding taken from https://pytorch.org/tutorials/beginner/transformer_tutorial.html

2022-10-14 17:05 UTC, jdiaz4302 commented on 02_train/src/B_FitBasicTransformer.ipynb
> +    "        self.dense_activation = nn.Sigmoid()\n",
Model structure:

- Embedding (dense layer) to project the input data to the transformer model size (functions similarly to a word embedding generator)
- A mask is used to prevent looking into the future
- A transformer encoder with self-attention is used to transform the embedding
- A dense layer acts on the encoder's output

During the forward pass, the positional encoding is added prior to the encoder.

2022-10-14 17:06 UTC, jdiaz4302 commented on 02_train/src/B_FitBasicTransformer.md
>          return out
Model structure:

- Embedding (dense layer) to project the input data to the transformer model size (functions similarly to a word embedding generator)
- A mask is used to prevent looking into the future
- A transformer encoder with self-attention is used to transform the embedding
- A dense layer acts on the encoder's output

During the forward pass, the positional encoding is added prior to the encoder.

2022-10-14 17:07 UTC, jdiaz4302 commented on 02_train/src/B_FitBasicTransformer.md
> +        return self.dropout(x)
This is a standard sinusoidal positional encoding taken from https://pytorch.org/tutorials/beginner/transformer_tutorial.html

2022-10-14 17:08 UTC, jdiaz4302 commented on 02_train/src/C_FitBasicLSTM_Large.ipynb
> +    "# which was originally y = 11*4*x + 4*x*x + 4*x + 1*x + 1\n",
Glimpse at the math used to match LSTM and transformer model size

2022-10-14 17:09 UTC, jdiaz4302 commented on 02_train/src/C_FitBasicLSTM_Large.md
> +# which was originally y = 11*4*x + 4*x*x + 4*x + 1*x + 1
Glimpse at the math used to match LSTM and transformer model size

2022-10-14 17:11 UTC, jdiaz4302 commented on 02_train/src/C_FitBasicLSTM_Large.md
> +# which was originally y = 11*4*x + 4*x*x + 4*x + 1*x + 1
Subsequent prints verify that the number of parameters is highly comparable (can't literally match due to different structures, but its ~99% matched)

2022-10-18 18:54 UTC, AndyMcAliley requested changes
Looks good! See my comment in the forward method of the BasicTransformer class for one implementation detail to double check before merging.

2022-10-18 18:54 UTC, AndyMcAliley commented on 02_train/src/E_FitBasicLSTM_Massive.md
> +nlayers = 6
Woo, this one is tougher. So, six layers. The first layer has 11 features, so it's like before: 4x(11+x) weights and 4x biases. The other five layers have x features, so they have 4x(x+x) weights and 4x biases. Then there's the final densely connected layer with x*1 weights and 1 bias. In total,

$y = 4x(11+x)+4x+5(4x(x+x)+4x)+1x+1$
$y = 44x+4x^2+4x+5(8x^2+4x)+1x+1$
$y = 44x^2+69x+1$

Solving for x,

$x = \frac{1}{2(44)}(-69 \pm \sqrt{69^2-4(44)(1-y))}$

The positive root is

$x=\frac{1}{88}(\sqrt{4761-176+176y}-69)$
$x=\frac{1}{88}(\sqrt{4585+176y}-69)$

Looks good!

2022-10-18 18:54 UTC, AndyMcAliley commented on 02_train/src/F_FitBasicTransformer_Massive.md
> +        embed = embed + position
...And again, tagging just in case.

2022-10-18 19:22 UTC, jdiaz4302 commented on 02_train/src/B_FitBasicTransformer.md
> +        return self.dropout(x)
`nn.TransformerEncoderLayer` uses a default dropout value of `0.1` which I did not override, and I used this value for some small regularization with the LSTMs as well.

https://pytorch.org/docs/stable/generated/torch.nn.TransformerEncoderLayer.html

2022-10-18 19:24 UTC, jdiaz4302 commented on 02_train/src/B_FitBasicTransformer.md
> +        return self.dropout(x)
I saw no harm leaving the dropout there (in the positional encoding) since it seems to fit a broader pattern of using lots of low-magnitude dropout in most transformer layers

2022-10-18 19:27 UTC, AndyMcAliley commented on 02_train/src/B_FitBasicTransformer.md
> +        return self.dropout(x)
Sounds good!

2022-10-18 21:28 UTC, AndyMcAliley submitted a review, later dismissed
Looks good!

2022-10-19 20:44 UTC, AndyMcAliley approved these changes

2022-10-20 13:32 UTC, merged